import { Medicine } from './Model/Medicine.model';
import { Prescription } from './Model/Prescription.model';
import { Chamber } from './Model/Chamber.model';
import { Speciality } from './Model/Speciality.model';
import { Degree } from './Model/Degree.model';
import { Categories } from './Model/Categories.model';
import { UserAvatar } from './UserAvatar.model';
import { AddressBook } from './AddressBook.model';
import { Role } from './Role.model';
import { DoctorSlot } from './Model/DoctorSlot.model';

export class User{
    userId: number;
    name: string;
    email: string;
    mobileNumber: string;
    password: string;
    gender: string;
    weight: number;
    age: number;
    bloodGroup: string;
    hospitalName: string;
    roles: Role;
    addressBooks: AddressBook;
    userAvatar: UserAvatar;
    account: Account[] = [];
    categories: Categories[] = [];
    degree: Degree;
    speciality: Speciality;
    chambers: Chamber[] = [];
    doctorSlots: DoctorSlot[] = [];
    prescriptions: Prescription[] = [];
    adminNumber: string;
    archived: boolean;
    adminFee: string;
    adminSecondTimeFee: string;
    doctorFee: string;
    doctorSecondTimeFee: string;
    agentCommisionPerAppoinment: number;
    todaysAppoinments: number = null;
    completeAppoinments: number = null;
    totalIncome: number = null;
    countUsers: number = null;
    countDoctors: number = null;
} 